import { supabase } from '@/integrations/supabase/client';
import { EmployeeUnified, mapDatabaseToUnified, mapUnifiedToDatabase } from '@/types/employee-unified';
import { EmployeeSoftDeleteService } from './EmployeeSoftDeleteService';

export class EmployeeService {
  /**
   * Get current user's company ID
   */
  private static async getCurrentUserCompanyId(): Promise<string | null> {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return null;

      const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('user_id', user.id)
        .single();

      return profile?.company_id || null;
    } catch (error) {
      console.error('Error getting company ID:', error);
      return null;
    }
  }

  /**
   * Get all employees for the current company (excluding soft deleted)
   */
  static async getEmployees(): Promise<{ success: boolean; data?: EmployeeUnified[]; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Fetching employees');
      
      // Get current user's company ID
      const companyId = await this.getCurrentUserCompanyId();
      if (!companyId) {
        console.error('❌ EmployeeService: No company ID found for current user');
        return { success: false, error: 'No se pudo determinar la empresa del usuario' };
      }

      console.log(`🔍 EmployeeService: Filtering employees for company: ${companyId}`);
      
      const { data, error } = await supabase
        .from('employees')
        .select('*')
        .eq('company_id', companyId) // ✅ FILTER by company
        .neq('estado', 'eliminado') // ✅ EXCLUDE soft deleted employees
        .order('created_at', { ascending: false });

      if (error) {
        console.error('❌ EmployeeService: Error fetching employees:', error);
        throw error;
      }

      if (!data) {
        console.log('⚠️ EmployeeService: No employees found');
        return { success: true, data: [] };
      }

      // Map database records to EmployeeUnified format
      const employees = data.map(mapDatabaseToUnified);
      
      console.log(`✅ EmployeeService: Successfully fetched ${employees.length} employees for company ${companyId}`);
      return { success: true, data: employees };
    } catch (error) {
      console.error('❌ EmployeeService: Error in getEmployees:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Get employee by ID (excluding soft deleted)
   */
  static async getEmployeeById(id: string): Promise<EmployeeUnified | null> {
    try {
      console.log('🔄 EmployeeService: Fetching employee by ID:', id);
      
      // Get current user's company ID
      const companyId = await this.getCurrentUserCompanyId();
      if (!companyId) {
        console.error('❌ EmployeeService: No company ID found for current user');
        return null;
      }
      
      const { data, error } = await supabase
        .from('employees')
        .select('*')
        .eq('id', id)
        .eq('company_id', companyId) // ✅ FILTER by company
        .neq('estado', 'eliminado') // ✅ EXCLUDE soft deleted employees
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error fetching employee:', error);
        throw error;
      }

      if (!data) {
        console.log('⚠️ EmployeeService: Employee not found:', id);
        return null;
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully fetched employee:', employee.nombre, employee.apellido);
      return employee;
    } catch (error) {
      console.error('❌ EmployeeService: Error in getEmployeeById:', error);
      return null;
    }
  }

  /**
   * Create new employee
   */
  static async createEmployee(employeeData: Omit<EmployeeUnified, 'id'>): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Creating employee:', employeeData.nombre, employeeData.apellido);
      
      // Map to database format
      const dbData = mapUnifiedToDatabase({
        ...employeeData,
        id: '', // Temporary ID, will be generated by database
        empresaId: employeeData.empresaId || employeeData.company_id || ''
      });

      const { data, error } = await supabase
        .from('employees')
        .insert(dbData)
        .select()
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error creating employee:', error);
        throw error;
      }

      if (!data) {
        throw new Error('No data returned from employee creation');
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully created employee:', employee.nombre, employee.apellido);
      return { success: true, data: employee };
    } catch (error) {
      console.error('❌ EmployeeService: Error in createEmployee:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Update employee
   */
  static async updateEmployee(id: string, updates: Partial<EmployeeUnified>): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Updating employee:', id);
      
      // Map to database format, but only the fields that are being updated
      const dbUpdates = mapUnifiedToDatabase({
        ...updates,
        id: id,
        empresaId: updates.empresaId || updates.company_id || ''
      } as EmployeeUnified);

      // Remove fields that shouldn't be updated
      delete dbUpdates.company_id; // This shouldn't change
      
      const { data, error } = await supabase
        .from('employees')
        .update(dbUpdates)
        .eq('id', id)
        .neq('estado', 'eliminado') // ✅ PREVENT updating soft deleted employees
        .select()
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error updating employee:', error);
        throw error;
      }

      if (!data) {
        throw new Error('No data returned from employee update');
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully updated employee:', employee.nombre, employee.apellido);
      return { success: true, data: employee };
    } catch (error) {
      console.error('❌ EmployeeService: Error in updateEmployee:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Delete employee (soft delete - changes status to 'eliminado')
   */
  static async deleteEmployee(id: string): Promise<{ success: boolean; error?: string }> {
    console.log('🔄 EmployeeService: Soft deleting employee:', id);
    return EmployeeSoftDeleteService.softDeleteEmployee(id);
  }

  /**
   * Get deleted employees (for recovery purposes)
   */
  static async getDeletedEmployees(): Promise<{ success: boolean; data?: EmployeeUnified[]; error?: string }> {
    return EmployeeSoftDeleteService.getDeletedEmployees();
  }

  /**
   * Restore a soft deleted employee
   */
  static async restoreEmployee(id: string): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    return EmployeeSoftDeleteService.restoreEmployee(id);
  }

  /**
   * Bulk delete employees (soft delete - changes status to 'eliminado')
   */
  static async bulkDeleteEmployees(employeeIds: string[]): Promise<{ success: boolean; results: { successful: number; failed: number; errors: string[] }; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Bulk deleting employees:', employeeIds.length);
      
      const results = {
        successful: 0,
        failed: 0,
        errors: [] as string[]
      };

      // Process each employee deletion
      for (const employeeId of employeeIds) {
        try {
          const result = await EmployeeSoftDeleteService.softDeleteEmployee(employeeId);
          if (result.success) {
            results.successful++;
          } else {
            results.failed++;
            results.errors.push(`Error eliminando empleado ${employeeId}: ${result.error}`);
          }
        } catch (error) {
          results.failed++;
          results.errors.push(`Error eliminando empleado ${employeeId}: ${error instanceof Error ? error.message : 'Error desconocido'}`);
        }
      }

      console.log(`✅ EmployeeService: Bulk delete completed - ${results.successful} successful, ${results.failed} failed`);
      return { success: true, results };
    } catch (error) {
      console.error('❌ EmployeeService: Error in bulkDeleteEmployees:', error);
      return { 
        success: false, 
        results: { successful: 0, failed: employeeIds.length, errors: [] },
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Bulk update employee status
   */
  static async bulkUpdateStatus(employeeIds: string[], newStatus: 'activo' | 'inactivo' | 'eliminado'): Promise<{ success: boolean; results: { successful: number; failed: number; errors: string[] }; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Bulk updating employee status:', employeeIds.length, 'to', newStatus);
      
      const results = {
        successful: 0,
        failed: 0,
        errors: [] as string[]
      };

      // Process each employee update
      for (const employeeId of employeeIds) {
        try {
          const result = await this.updateEmployee(employeeId, { estado: newStatus });
          if (result.success) {
            results.successful++;
          } else {
            results.failed++;
            results.errors.push(`Error actualizando empleado ${employeeId}: ${result.error}`);
          }
        } catch (error) {
          results.failed++;
          results.errors.push(`Error actualizando empleado ${employeeId}: ${error instanceof Error ? error.message : 'Error desconocido'}`);
        }
      }

      console.log(`✅ EmployeeService: Bulk update completed - ${results.successful} successful, ${results.failed} failed`);
      return { success: true, results };
    } catch (error) {
      console.error('❌ EmployeeService: Error in bulkUpdateStatus:', error);
      return { 
        success: false, 
        results: { successful: 0, failed: employeeIds.length, errors: [] },
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }
}
