
import { supabase } from '@/integrations/supabase/client';
import { EmployeeUnified, mapDatabaseToUnified, mapUnifiedToDatabase } from '@/types/employee-unified';
import { EmployeeSoftDeleteService } from './EmployeeSoftDeleteService';

export class EmployeeService {
  /**
   * Get all employees for the current company (excluding soft deleted)
   */
  static async getEmployees(): Promise<{ success: boolean; data?: EmployeeUnified[]; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Fetching employees');
      
      const { data, error } = await supabase
        .from('employees')
        .select('*')
        .neq('estado', 'eliminado') // ✅ EXCLUDE soft deleted employees
        .order('created_at', { ascending: false });

      if (error) {
        console.error('❌ EmployeeService: Error fetching employees:', error);
        throw error;
      }

      if (!data) {
        console.log('⚠️ EmployeeService: No employees found');
        return { success: true, data: [] };
      }

      // Map database records to EmployeeUnified format
      const employees = data.map(mapDatabaseToUnified);
      
      console.log(`✅ EmployeeService: Successfully fetched ${employees.length} employees`);
      return { success: true, data: employees };
    } catch (error) {
      console.error('❌ EmployeeService: Error in getEmployees:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Get employee by ID (excluding soft deleted)
   */
  static async getEmployeeById(id: string): Promise<EmployeeUnified | null> {
    try {
      console.log('🔄 EmployeeService: Fetching employee by ID:', id);
      
      const { data, error } = await supabase
        .from('employees')
        .select('*')
        .eq('id', id)
        .neq('estado', 'eliminado') // ✅ EXCLUDE soft deleted employees
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error fetching employee:', error);
        throw error;
      }

      if (!data) {
        console.log('⚠️ EmployeeService: Employee not found:', id);
        return null;
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully fetched employee:', employee.nombre, employee.apellido);
      return employee;
    } catch (error) {
      console.error('❌ EmployeeService: Error in getEmployeeById:', error);
      return null;
    }
  }

  /**
   * Create new employee
   */
  static async createEmployee(employeeData: Omit<EmployeeUnified, 'id'>): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Creating employee:', employeeData.nombre, employeeData.apellido);
      
      // Map to database format
      const dbData = mapUnifiedToDatabase({
        ...employeeData,
        id: '', // Temporary ID, will be generated by database
        empresaId: employeeData.empresaId || employeeData.company_id || ''
      });

      const { data, error } = await supabase
        .from('employees')
        .insert(dbData)
        .select()
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error creating employee:', error);
        throw error;
      }

      if (!data) {
        throw new Error('No data returned from employee creation');
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully created employee:', employee.nombre, employee.apellido);
      return { success: true, data: employee };
    } catch (error) {
      console.error('❌ EmployeeService: Error in createEmployee:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Update employee
   */
  static async updateEmployee(id: string, updates: Partial<EmployeeUnified>): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    try {
      console.log('🔄 EmployeeService: Updating employee:', id);
      
      // Map to database format, but only the fields that are being updated
      const dbUpdates = mapUnifiedToDatabase({
        ...updates,
        id: id,
        empresaId: updates.empresaId || updates.company_id || ''
      } as EmployeeUnified);

      // Remove fields that shouldn't be updated
      delete dbUpdates.company_id; // This shouldn't change
      
      const { data, error } = await supabase
        .from('employees')
        .update(dbUpdates)
        .eq('id', id)
        .neq('estado', 'eliminado') // ✅ PREVENT updating soft deleted employees
        .select()
        .single();

      if (error) {
        console.error('❌ EmployeeService: Error updating employee:', error);
        throw error;
      }

      if (!data) {
        throw new Error('No data returned from employee update');
      }

      const employee = mapDatabaseToUnified(data);
      console.log('✅ EmployeeService: Successfully updated employee:', employee.nombre, employee.apellido);
      return { success: true, data: employee };
    } catch (error) {
      console.error('❌ EmployeeService: Error in updateEmployee:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Error desconocido' 
      };
    }
  }

  /**
   * Delete employee (soft delete - changes status to 'eliminado')
   */
  static async deleteEmployee(id: string): Promise<{ success: boolean; error?: string }> {
    console.log('🔄 EmployeeService: Soft deleting employee:', id);
    return EmployeeSoftDeleteService.softDeleteEmployee(id);
  }

  /**
   * Get deleted employees (for recovery purposes)
   */
  static async getDeletedEmployees(): Promise<{ success: boolean; data?: EmployeeUnified[]; error?: string }> {
    return EmployeeSoftDeleteService.getDeletedEmployees();
  }

  /**
   * Restore a soft deleted employee
   */
  static async restoreEmployee(id: string): Promise<{ success: boolean; data?: EmployeeUnified; error?: string }> {
    return EmployeeSoftDeleteService.restoreEmployee(id);
  }
}
