// This file is automatically generated. Do not edit it directly.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface RecalcRequest {
  action: string;
  data: {
    period_id: string;
    company_id: string;
  };
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabaseClient = createClient(supabaseUrl, supabaseKey)

    // Parse request
    const requestBody: RecalcRequest = await req.json()
    console.log('🔄 IBC Recalculation Request:', requestBody)

    const { action, data } = requestBody

    if (action === 'recalculate_ibc') {
      console.log(`🚀 Starting IBC recalculation for period: ${data.period_id}`)

      // Get payroll data with employee info
      const { data: payrollsData, error: payrollsDataError } = await supabaseClient
        .from('payrolls')
        .select(`
          *,
          employees!inner(salario_base)
        `)
        .eq('period_id', data.period_id)
        .eq('company_id', data.company_id)

      if (payrollsDataError) {
        throw new Error(`Error fetching payrolls: ${payrollsDataError.message}`)
      }

      let processedCount = 0

      // Process each payroll to recalculate accurate IBC
      for (const payroll of payrollsData || []) {
        try {
          const salarioBase = payroll.employees?.salario_base || 0
          const diasTrabajados = payroll.dias_trabajados || 30
          
          // Get novedades for this employee in this period
          const { data: novedades } = await supabaseClient
            .from('payroll_novedades')
            .select('tipo_novedad, valor')
            .eq('periodo_id', data.period_id)
            .eq('empleado_id', payroll.employee_id)

          // Calculate constitutive novedades
          const constitutiveTypes = ['horas_extra', 'recargo_nocturno', 'recargo_dominical', 'comision', 'bonificacion', 'vacaciones', 'licencia_remunerada', 'auxilio_conectividad']
          const novedadesConstitutivas = (novedades || [])
            .filter(n => constitutiveTypes.includes(n.tipo_novedad))
            .reduce((sum, n) => sum + (n.valor || 0), 0)

          // Calculate exact proportional IBC: (base_salary / 30 * dias_trabajados) + constitutive_novedades
          const ibcBase = (salarioBase / 30) * diasTrabajados
          let ibc = ibcBase + novedadesConstitutivas
          
          // Apply maximum cap only (25 SMMLV) - no minimum to preserve exact calculation
          const SMMLV_2025 = 1300000
          ibc = Math.min(ibc, SMMLV_2025 * 25)

          // Calculate other fields
          const transportAllowance = salarioBase <= (SMMLV_2025 * 2) ? (200000 / 30) * diasTrabajados : 0
          const healthDeduction = ibc * 0.04
          const pensionDeduction = ibc * 0.04

          console.log(`📊 Recalculating employee ${payroll.employee_id}: IBC ${ibc} (was: ${payroll.ibc})`)

          // Update payroll with corrected values
          const { error: updateError } = await supabaseClient
            .from('payrolls')
            .update({ 
              ibc: Math.round(ibc),
              auxilio_transporte: Math.round(transportAllowance),
              salud_empleado: Math.round(healthDeduction),
              pension_empleado: Math.round(pensionDeduction),
              updated_at: new Date().toISOString() 
            })
            .eq('id', payroll.id)

          if (updateError) {
            console.error(`❌ Error updating payroll ${payroll.id}:`, updateError)
          } else {
            processedCount++
          }

        } catch (employeeError) {
          console.error(`❌ Error processing payroll ${payroll.id}:`, employeeError)
        }
      }

      // Update period totals
      const { data: updatedPayrolls } = await supabaseClient
        .from('payrolls')
        .select('total_devengado, total_deducciones, neto_pagado')
        .eq('period_id', data.period_id)

      if (updatedPayrolls) {
        const totals = updatedPayrolls.reduce((acc, p) => ({
          devengado: acc.devengado + (p.total_devengado || 0),
          deducciones: acc.deducciones + (p.total_deducciones || 0),
          neto: acc.neto + (p.neto_pagado || 0)
        }), { devengado: 0, deducciones: 0, neto: 0 })

        await supabaseClient
          .from('payroll_periods_real')
          .update({
            total_devengado: totals.devengado,
            total_deducciones: totals.deducciones,
            total_neto: totals.neto,
            updated_at: new Date().toISOString()
          })
          .eq('id', data.period_id)
      }

      console.log(`✅ IBC recalculation completed: ${processedCount} employees processed`)

      return new Response(
        JSON.stringify({
          success: true,
          employees_processed: processedCount,
          period_id: data.period_id
        }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    return new Response(
      JSON.stringify({ error: 'Invalid action' }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400 
      }
    )

  } catch (error) {
    console.error('❌ IBC Recalculation Error:', error)
    return new Response(
      JSON.stringify({ 
        error: error.message,
        success: false 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    )
  }
})