
import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { Bot, User } from 'lucide-react';

interface NovedadAutoIndicatorProps {
  isAutoGenerated?: boolean;
  isPartial?: boolean;
  originalAbsenceId?: string;
  className?: string;
}

export const NovedadAutoIndicator = ({ 
  isAutoGenerated = false, 
  isPartial = false,
  originalAbsenceId,
  className = "" 
}: NovedadAutoIndicatorProps) => {
  if (!isAutoGenerated) {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Badge variant="outline" className={`bg-blue-50 border-blue-200 text-blue-700 ${className}`}>
              <User className="h-3 w-3 mr-1" />
              Manual
            </Badge>
          </TooltipTrigger>
          <TooltipContent>
            <p>Novedad ingresada manualmente</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return (
    <div className="flex items-center space-x-1">
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Badge variant="outline" className={`bg-purple-50 border-purple-200 text-purple-700 ${className}`}>
              <Bot className="h-3 w-3 mr-1" />
              Auto
            </Badge>
          </TooltipTrigger>
          <TooltipContent>
            <p>Novedad generada automáticamente desde ausencia</p>
            {originalAbsenceId && (
              <p className="text-xs text-muted-foreground mt-1">
                ID: {originalAbsenceId}
              </p>
            )}
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>

      {isPartial && (
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <Badge variant="outline" className={`bg-orange-50 border-orange-200 text-orange-700 ${className}`}>
                Parcial
              </Badge>
            </TooltipTrigger>
            <TooltipContent>
              <p>Novedad parcial - La ausencia original cruza múltiples períodos</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      )}
    </div>
  );
};
